name: Published Release
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dump Github context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
        echo "${{ github.event.release.tag_name }}"
        echo "${{ github.event.release.body }}"
        echo "${{ github.actor }}"
    
